---

- name: Create Temp directory
  file: path={{ tmp_location }} state=directory mode=0755

- name: Download and extract local copy of installer
  unarchive:
    src: "{{ media_host }}/software/ibm/installation_manager/{{ version }}/agent.installer.{{ platform }}.gtk.{{ architecture }}_{{ version_tag }}.zip"
    dest: "{{ tmp_location }}"
    remote_src: yes

- name: Run silent install to {{ ibmim_install_location }}
  command:
    chdir={{ tmp_location }}
    {{ tmp_location }}/install -acceptLicense --launcher.ini silent-install.ini
    creates={{ ibmim_install_location }}
  register: install
  changed_when: install.rc != 0

- name: Remove Installer
  file: path={{ tmp_location }} state=absent
